version: "2"
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
    - errcheck
    - errorlint
    - exhaustive
    - forbidigo
    - forcetypeassert
    - goconst
    - gocritic
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nilerr
    - prealloc
    - reassign
    - revive
    - staticcheck
    - unconvert
    - unused
    - varnamelen
    - whitespace
  settings:
    depguard:
      rules:
        main:
          files:
            - $all
            - '!$test'
          allow:
            - $gostd
            - github.com/grafana/okta-logs-collector/metadata
            - github.com/okta/okta-sdk-golang/v2/
            - github.com/pirsquare/country-mapper
            - github.com/sirupsen/logrus
            - github.com/urfave/cli/v3
        test:
          files:
            - $test
          allow:
            - $gostd
            - github.com/jarcoal/httpmock
            - github.com/stretchr/testify
            - github.com/okta/okta-sdk-golang/v2
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
